### ISSUE TITLE
New Bug

### ISSUE THREAD

**Issue by LuomingXu** [Yihy/resources_cn#2]
我将其改为了resources_cn.jar之后, 在首页, 不可以使用IDE的那个"设置", 点了之后没有反应, 不知是何缘故, 改为原来的_en之后就好了, 就可以会弹出settings窗口了
版本:community2.5
win10-1709

**Comment by Yihy** [comment]
我用旗舰版试了一下没问题。社区版我稍后下载一个检查下问题
