### ISSUE TITLE
Git历史记录窗口不能正常弹出的问题

### ISSUE THREAD

**Issue by yihuishou** [Yihy/resources_cn#3]
`messages/UIBundle.properties`

**tool.window.name.version.control=Version Control** 这个不能被汉化吧

**Comment by Yihy** [comment]
确实不能弹出,包括SVN,之前我就发现了,但是未找到解决的办法,这个是解决的吗?我测试一下

**Comment by Yihy** [comment]
确实.谢谢你的帮助,哈哈
