### ISSUE TITLE
萌新求教一个问题~~

### ISSUE THREAD

**Issue by yihuishou** [Yihy/resources_cn#4]
![question](https://user-images.githubusercontent.com/26241263/33365243-880562c0-d522-11e7-923b-205738f14b4d.jpg)

这里的复制路径的翻译项始终未能找到，大佬知道怎么才能翻译这个吗？

**Comment by Yihy** [comment]
这个翻译不了,这句话没有抽取出来.

**Comment by yihuishou** [comment]
不是plugs里的？

**Comment by Yihy** [comment]
没有,插件包里没有
