### ISSUE TITLE
官方的配置文件是不是有问题？

### ISSUE THREAD

**Issue by yihuishou** [Yihy/resources_cn#6]
`RefactoringBundle.properties`
Line 346：  copy,handler.clone.files.directories=克隆文件/目录

这个copy后面用了`,` 这个是不是用错了？

**Comment by Yihy** [comment]
资源文件

key只要是string就可以,不管逗号还是点.不规范是肯定的
原版里面也是逗号
![asf](https://user-images.githubusercontent.com/18240360/33416995-6c2b2b8a-d5da-11e7-84bb-c60cb22a6307.png)

**Comment by Yihy** [comment]
用着应该没问题吧
