### ISSUE TITLE
两个实体生成的代码字段对不上

### ISSUE THREAD

**Issue by mwylaoma** [Yihy/resources_cn#7]
![aef8b7fb-f243-4e1a-8e1f-6c543e5fc299](https://user-images.githubusercontent.com/3048280/33750323-27cd3688-dc0e-11e7-95bc-649cd6617653.png)

字段对不上，请看图
Idea版本是2017.3.1 RC

**Comment by Yihy** [comment]
插件的问题不要在这里回复
请把不需要的勾选项去掉

**Comment by mwylaoma** [comment]
好的，已经去掉过的了，请问在哪里回复？

**Comment by Yihy** [comment]
[DTOUtils-IDEA-Plugin](https://github.com/Yihy/DTOUtils-IDEA-Plugin)
